// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IRiscZeroVerifier
/// @notice Interface for the RISC Zero Groth16 Verifier
interface IRiscZeroVerifier {
    function verify(bytes calldata seal, bytes32 imageId, bytes32 postStateDigest) external view;
}

/// @title LoreZKVerifierLedger
/// @notice A cryptographic ledger that ONLY accepts ZK-SNARK proven behavioral traces.
contract LoreZKVerifierLedger {
    // The official RISC Zero Verifier contract address (e.g., on Ethereum/Base/Arbitrum)
    IRiscZeroVerifier public immutable verifier;

    // The Image ID of the specific `zk-circuit-guest` program compiled by RISC Zero.
    // This guarantees that ONLY our exact verification rules were executed.
    bytes32 public immutable guestImageId;

    // Maps a public journal (Merkle root or CID) to its verified status
    mapping(bytes32 => bool) public verifiedJournals;

    event ZKProofCommitted(bytes32 indexed journalDigest, uint256 timestamp);

    constructor(address _verifier, bytes32 _guestImageId) {
        verifier = IRiscZeroVerifier(_verifier);
        guestImageId = _guestImageId;
    }

    /// @notice Submits a ZK-SNARK proof of correct execution.
    /// @param seal The Groth16 cryptographic proof generated by the ZKVM.
    /// @param journalDigest The sha256 hash of the public output (e.g. the Merkle Root or IPFS CID).
    function commitVerifiedTrace(bytes calldata seal, bytes32 journalDigest) external {
        // Prevent replay attacks
        require(!verifiedJournals[journalDigest], "Journal already verified and committed");

        // 1. Math Verification: The smart contract calls the RISC Zero verifier.
        // It checks the mathematical proof (seal) against the specific guestImageId and the public output (journalDigest).
        // If the agent hallucinated, altered the rules, or used the wrong ZK circuit, this will REVERT.
        verifier.verify(seal, guestImageId, journalDigest);

        // 2. State Update: If the verification mathematically succeeds, we mark the trace as verified.
        verifiedJournals[journalDigest] = true;

        // 3. Emit on-chain event for the frontend/subgraphs to pick up
        emit ZKProofCommitted(journalDigest, block.timestamp);
    }
}
